# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

POST http://172.22.240.1:3004/token
Content-Type: application/x-www-form-urlencoded

username = iradi &
password = sky-licht

###
GET http://172.22.240.1:3004/api/v1/line_balance/get_by_id?line_balance_id=Zkr7KWi1PWtz568
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJpcmFkaSIsImV4cCI6MTczNjU1MTc4MH0.hEkT_6PjnBtoCNkM_9g-qD8rhCvB15TqAMIRwvIYlCI
Accept: application/json

###